# serverless.yml
#使用教程 https://github.com/llh1347/scf-checkbox
#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: checkbox # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-guangzhou # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: 
    - timer: #触发器
        parameters:
          name: checkbox
          cronExpression: " 3 8 * * *"
          enable: true
          argument: 
  environment: #  环境变量
    variables: #  环境变量对象
      
